package slots;

import DAO.implementaciones.DiscoDAOImpl;
import DAO.interfaces.DiscoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.DiscoModel;

import visuals.LayoutAdmin;

/**
 *
 * @author U22244028
 */
public class Discos extends javax.swing.JPanel {

    /**
     * Creates new form Discos
     */
    public Discos() {
        initComponents();
        tablaDiscos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDiscos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaDiscos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Proveedor", "Nombre", "Tipo", "Capacidad", "Interfaz", "Lectura", "Escritura", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(TablaDiscos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 760, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 22, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        jButton2.setText("AGREGAR STOCK");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jLabel1.setText("CANTIDAD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 70, 30));

        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 30, -1));

        jTextField2.setEditable(false);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdministarProductos ingreso = new AdministarProductos();
        LayoutAdmin.getInstance().switchPanel(ingreso);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int rowDisk = TablaDiscos.getSelectedRow();
        if(rowDisk == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DiscoModel disco = new DiscoModel();
        String diskId = (String) TablaDiscos.getValueAt(rowDisk, 0);
        disco.setDiskId(diskId);
        DiscoDAO dao = new DiscoDAOImpl();
        try {
            dao.delete(disco);
            JOptionPane.showMessageDialog(null, "Eliminado correctamente");
            tablaDiscos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ah ocurrido un error, el no se a eliminado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        RegistrarDisco regDisco = new RegistrarDisco();
        LayoutAdmin.getInstance().switchPanel(regDisco);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int rowUser = TablaDiscos.getSelectedRow();
        if(rowUser == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DiscoModel disco = new DiscoModel();
        disco.setDiskId((String) TablaDiscos.getValueAt(rowUser, 0));
        disco.setSupplierId((Integer) TablaDiscos.getValueAt(rowUser, 1));
        disco.setName((String) TablaDiscos.getValueAt(rowUser, 2));
        disco.setType((String) TablaDiscos.getValueAt(rowUser, 3));
        disco.setCapacity((Integer) TablaDiscos.getValueAt(rowUser, 4));
        disco.setInterface((String) TablaDiscos.getValueAt(rowUser, 5));
        disco.setReadSpeed((Integer) TablaDiscos.getValueAt(rowUser, 6));
        disco.setWriteSpeed((Integer) TablaDiscos.getValueAt(rowUser, 7));
        disco.setQuantity((Integer) TablaDiscos.getValueAt(rowUser, 8));
        EditarDisco editDisco = new EditarDisco(disco);
        LayoutAdmin.getInstance().switchPanel(editDisco);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tablaDiscos(){
        try {
            DiscoDAO dao = new DiscoDAOImpl();
            DefaultTableModel model = (DefaultTableModel) TablaDiscos.getModel();
            model.setRowCount(0);
            dao.readAll().forEach((u -> model.addRow(new Object[]{
                u.getDiskId(),
                u.getSupplierId(),
                u.getName(),
                u.getType(),
                u.getCapacity(),
                u.getInterface(),
                u.getReadSpeed(),
                u.getWriteSpeed(),
                u.getQuantity(),
            })));
        } catch (Exception e) {
            System.err.print(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDiscos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
